### ISSUE TITLE
12061 Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#21]
with FP 2.7.8 and BIOS 0.7.16:
```
11.11.2018 05:37:00  version : 1.0.104.5289
666 Custom message = [Via SaitekPanel.SetLastException()]
System.Exception
DCSBIOSControlLocator.GetDCSBIOSOutput() Should not be called when only key emulator is active
   at DCS_BIOS.DCSBIOSControlLocator.GetDCSBIOSOutput(String controlId)
   at NonVisuals.RadioPanelPZ69Ka50.Startup()
11.11.2018 05:37:00  version : 1.0.104.5289
12061 Custom message = []
System.NullReferenceException
Object reference not set to an instance of an object.
   at DCS_BIOS.DCSBIOSInput.Consume(DCSBIOSControl dcsbiosControl)
   at DCS_BIOS.DCSBIOSInput.ImportString(String str)
   at NonVisuals.DCSBIOSBindingPZ55.ImportSettings(String settings)
   at NonVisuals.SwitchPanelPZ55.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()
```

**Comment by jdahlblom** [comment]
How do I reproduce this?
