### ISSUE TITLE
Failed to find control ALT_MSL_FT for airframe Mi-8MT (Mi-8MT.json)

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#22]
with FP 2.7.8 and BIOS 0.7.16, Mi-8 profile with NS430 enabled
```
11.11.2018 05:50:35  version : 1.0.104.5289
12061 Custom message = []
System.Exception
Check DCS-BIOS version. Failed to find control ALT_MSL_FT for airframe Mi-8MT (Mi-8MT.json). Did you switch airframe type for the profile and have existing control(s) for the previous type saved?
Sequence contains more than one matching element
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSOutput.ImportString(String str)
   at NonVisuals.DCSBIOSBindingLCDPZ70.ImportSettings(String settings)
   at NonVisuals.MultiPanelPZ70.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()
```

**Comment by jdahlblom** [comment]
Is this when you open an existing profile? If so can you please post the profile here. I will fix it asap.

**Comment by emcek** [comment]
1. Open FP
2. be sure no profile is loaded
3. enable NS 430 option
3. load Flight Panel Mi8.bindings
[Flight Panel Mi8.bindings.txt](https://github.com/DCSFlightpanels/DCSFlightpanels/files/2569666/Flight.Panel.Mi8.bindings.txt)

**Comment by emcek** [comment]
I'm out of home for week, I can confirm it next Monday ;)

**Comment by emcek** [comment]
Update FP 2.7.9.6600 and BIOS to 07.17. I did the same procedure as previously and:
```
19.11.2018 06:49:23  version : 1.0.105.6600
666 Custom message = [Via SaitekPanel.SetLastException()]
System.Exception
LoadControls() : 
Failed to find DCS-BIOS files. -> 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json'.
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSControlLocator.GetDCSBIOSOutput(String controlId)
   at NonVisuals.RadioPanelPZ69P51D.Startup()
19.11.2018 06:49:23  version : 1.0.105.6600
12061 Custom message = []
System.Exception
LoadControls() : 
Failed to find DCS-BIOS files. -> 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json'.
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSInput.ImportString(String str)
   at NonVisuals.DCSBIOSBindingPZ55.ImportSettings(String settings)
   at NonVisuals.SwitchPanelPZ55.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()
19.11.2018 06:49:35  version : 1.0.105.6600
666 Custom message = [Via SaitekPanel.SetLastException()]
System.Exception
LoadControls() : 
Failed to find DCS-BIOS files. -> 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json'.
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSControlLocator.GetDCSBIOSOutput(String controlId)
   at NonVisuals.RadioPanelPZ69Mi8.Startup()
19.11.2018 06:49:35  version : 1.0.105.6600
12061 Custom message = []
System.Exception
LoadControls() : 
Failed to find DCS-BIOS files. -> 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json'.
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls(String jsonDirectory, String profile)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSInput.ImportString(String str)
   at NonVisuals.DCSBIOSBindingPZ55.ImportSettings(String settings)
   at NonVisuals.SwitchPanelPZ55.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()
```
then close profile, disable NS430 and:
```
19.11.2018 06:49:56  version : 1.0.105.6600
12061 Custom message = []
System.Exception
LoadCommonData() : 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json\CommonData.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at DCS_BIOS.DCSBIOSControlLocator.LoadCommonData(String jsonDirectory)
   at DCS_BIOS.DCSBIOSControlLocator.LoadCommonData(String jsonDirectory)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSInput.ImportString(String str)
   at NonVisuals.DCSBIOSBindingPZ55.ImportSettings(String settings)
   at NonVisuals.SwitchPanelPZ55.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()
19.11.2018 06:50:19  version : 1.0.105.6600
1073 Custom message = []
System.Exception
LoadCommonData() : 
Could not find a part of the path 'C:\Users\mplic\Saved Games\DCS\Scripts\DCS-BIOS\doc\json\CommonData.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at DCS_BIOS.DCSBIOSControlLocator.LoadCommonData(String jsonDirectory)
   at DCS_BIOS.DCSBIOSControlLocator.LoadCommonData(String jsonDirectory)
   at DCS_BIOS.DCSBIOSControlLocator.LoadControls()
   at DCS_BIOS.DCSBIOSControlLocator.GetControl(String controlId)
   at DCS_BIOS.DCSBIOSControlLocator.GetDCSBIOSOutput(String controlId)
   at NonVisuals.SaitekPanel..ctor(SaitekPanelsEnum typeOfSaitekPanel, HIDSkeleton hidSkeleton)
   at NonVisuals.SwitchPanelPZ55..ctor(HIDSkeleton hidSkeleton)
   at DCSFlightpanels.SwitchPanelPZ55UserControl..ctor(HIDSkeleton hidSkeleton, TabItem parentTabItem, IGlobalHandler globalHandler)
   at DCSFlightpanels.MainWindow.SearchForPanels()
```

**Comment by emcek** [comment]
sorry with update path to BIOS was changes, when I corrected, issue was fixed!
