### ISSUE TITLE
PZ70 Multipanel FLAPS_LEVER_DOWN textbox not found

### ISSUE THREAD

**Issue by juusolain** [DCS-Skunkworks/DCSFlightpanels#26]
Version 2.8.1 Pre-release

If trying to load a .bindings-file with a binding for FLAPS_LEVER_DOWN, I get the following error:
```
25.12.2018 11.23.29  version : 1.0.116.7055
993013 Custom message = []
System.Exception
Failed to find TextBox MultiPanel knob FLAPS_LEVER_DOWN
   at DCSFlightpanels.MultiPanelUserControl.GetTextBox(MultiPanelPZ70Knobs knob, Boolean whenTurnedOn)
   at DCSFlightpanels.MultiPanelUserControl.ShowGraphicConfiguration()
```

If I try to save with something binded to FLAPS_LEVER_DOWN, it empties all bindings in multi-panel.

Here's my .bindings-file:

```
Airframe=P51D
OperationLevelFlag=3

PanelType=PZ70MultiPanel
PanelInstanceID=\\?\hid#vid_06a3&pid_0d06#8&9048cc7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
PanelSettingsVersion=2X
BeginPanel
	MultiPanelKnob{ALT}\o/{1FLAPS_LEVER_UP}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_F}
	MultiPanelKnob{ALT}\o/{1FLAPS_LEVER_DOWN}\o/OSKeyPress{FiftyMilliSec,VK_F}
	MultiPanelKnob{ALT}\o/{1AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,VK_A}
	MultiPanelKnob{ALT}\o/{0AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_9}
	MultiPanelKnob{VS}\o/{1FLAPS_LEVER_UP}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_F}
	MultiPanelKnob{VS}\o/{1FLAPS_LEVER_DOWN}\o/OSKeyPress{FiftyMilliSec,VK_F}
	MultiPanelKnob{VS}\o/{1AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,VK_A}
	MultiPanelKnob{VS}\o/{0AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_9}
	MultiPanelKnob{IAS}\o/{0AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_9}
	MultiPanelKnob{HDG}\o/{0AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_9}
	MultiPanelKnob{IAS}\o/{1AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,VK_A}
	MultiPanelKnob{HDG}\o/{1AP_BUTTON}\o/OSKeyPress{FiftyMilliSec,VK_A}
	MultiPanelKnob{IAS}\o/{1FLAPS_LEVER_UP}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_F}
	MultiPanelKnob{HDG}\o/{1FLAPS_LEVER_UP}\o/OSKeyPress{FiftyMilliSec,LCONTROL + VK_F}
	MultiPanelKnob{HDG}\o/{1FLAPS_LEVER_DOWN}\o/OSKeyPress{FiftyMilliSec,VK_F}
	MultiPanelKnob{IAS}\o/{1FLAPS_LEVER_DOWN}\o/OSKeyPress{FiftyMilliSec,VK_F}
	MultiPanelDCSBIOSControlLCD{ALT}\o/{UpperLCD}\o/DCSBiosOutput{ALT_MSL_FT|Equals|0}
	MultiPanelDCSBIOSControlLCD{ALT}\o/{LowerLCD}\o/DCSBiosOutput{AIRSPEED_MPH_VALUE|Equals|0}
EndPanel
```

**Comment by juusolain** [comment]
Works with version 2.7.16, so the problem should be 2.7.16 and 2.8.1.

**Comment by jdahlblom** [comment]
Thanks, found a bug in several locations regarding this. I will fix it today.

**Comment by juusolain** [comment]
Yeah, it works.
