### ISSUE TITLE
FLAPS_LEVER_DOWN textbox not found

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#28]
I have similar issue as #26 It started when I added FlapsDown (FLAPS=0)
I have: DCSFP 2.8.11 and BIOS 0.7.19
```
05.01.2019 07:03:55  version : 1.0.119.4471
993013 Custom message = []
System.Exception
Failed to find TextBox MultiPanel knob FLAPS_LEVER_DOWN
   at DCSFlightpanels.MultiPanelUserControl.GetTextBox(MultiPanelPZ70Knobs knob, Boolean whenTurnedOn)
   at DCSFlightpanels.MultiPanelUserControl.ShowGraphicConfiguration()
05.01.2019 07:04:37  version : 1.0.119.4471
993013 Custom message = []
System.Exception
Failed to find TextBox MultiPanel knob FLAPS_LEVER_DOWN
   at DCSFlightpanels.MultiPanelUserControl.GetTextBox(MultiPanelPZ70Knobs knob, Boolean whenTurnedOn)
   at DCSFlightpanels.MultiPanelUserControl.ShowGraphicConfiguration()
05.01.2019 07:04:37  version : 1.0.119.4471
993013 Custom message = []
System.Exception
Failed to find TextBox MultiPanel knob FLAPS_LEVER_DOWN
   at DCSFlightpanels.MultiPanelUserControl.GetTextBox(MultiPanelPZ70Knobs knob, Boolean whenTurnedOn)
   at DCSFlightpanels.MultiPanelUserControl.ShowGraphicConfiguration()
```
and this is profile:
```
PanelType=PZ55SwitchPanel
PanelInstanceID=\\?\hid#vid_06a3&pid_0d67#8&381ea06f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
PanelSettingsVersion=0X
BeginPanel
	SwitchPanelDCSBIOSControl{1SWITCHKEY_LIGHTS_NAV|NavOn}\o/\o/DCSBIOSInput{NAV_LIGHTS|SET_STATE|1|0}
	SwitchPanelDCSBIOSControl{0SWITCHKEY_LIGHTS_NAV|NavOff}\o/\o/DCSBIOSInput{NAV_LIGHTS|SET_STATE|0|0}
	SwitchPanelDCSBIOSControl{1SWITCHKEY_DE_ICE|DeIceOn}\o/\o/DCSBIOSInput{DEICER|SET_STATE|1|0}
	SwitchPanelDCSBIOSControl{0SWITCHKEY_DE_ICE|DeIceOff}\o/\o/DCSBIOSInput{DEICER|SET_STATE|0|0}
	ManualLandingGearLEDs{False}
EndPanel

PanelType=PZ70MultiPanel
PanelInstanceID=\\?\hid#vid_06a3&pid_0d06#8&3004aa58&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
PanelSettingsVersion=2X
BeginPanel
	MultiPanelDCSBIOSControl{ALT}\o/{1FLAPS_LEVER_UP|FlapsUp}\o/\o/DCSBIOSInput{FLAPS|SET_STATE|1|0}
	MultiPanelDCSBIOSControl{ALT}\o/{0FLAPS_LEVER_DOWN|DCS-BIOS}\o/\o/DCSBIOSInput{FLAPS|SET_STATE|0|0}
EndPanel
```

**Comment by jdahlblom** [comment]
Which airplane is it?

**Comment by emcek** [comment]
Spitfire IX

**Comment by jdahlblom** [comment]
OK. You need to change the second line to (1FLAPS_LEVER_DOWN):
MultiPanelDCSBIOSControl{ALT}\o/{1FLAPS_LEVER_DOWN|DCS-BIOS}\o/\o/DCSBIOSInput{FLAPS|SET_STATE|0|0}

Check https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/2.8.12

**Comment by emcek** [comment]
yes, fixed!
