### ISSUE TITLE
BUG: deleting streamdeck dsc-bios button action results in error

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#66]
set up any button with a dcs-bios action and then try to delete it to reproduce 

```
02.05.2020 04:05:59  version : 1.0.218.6063

System.Exception
Cannot insert KeyPress, Bill already contains DCSBIOSInputs
   at DCSFlightpanels.Bills.BillBaseInput.set_KeyPress(KeyPress value)
   at DCSFlightpanels.Bills.BillStreamDeckAction.Clear()
   at DCSFlightpanels.PanelUserControls.UserControlStreamDeckButtonAction.ButtonDeleteDCSBIOSActionButtonOn_OnClick(Object sender, RoutedEventArgs e)
```

![image](https://user-images.githubusercontent.com/2563358/80854759-f44aaa00-8c8e-11ea-8148-b2ee0e6b8c46.png)

**Comment by matt-cahill** [comment]
confirmed fixed in 4.0.30
