### ISSUE TITLE
F10 key can not be assigned to a keypress

### ISSUE THREAD

**Issue by shaky1963** [DCS-Skunkworks/DCSFlightpanels#71]
i cant assign the F10 key as a key press on the stream deck to bring up the map in dcs. All the other F1 to F12 keys i can assign. I also checked the switch panel, radio panel and multi panel and all have the same issue

**Comment by shaky1963** [comment]
I can now assign the F10 key. It now works for me. I will close this issue. 
I am going to do more testing tonight. I dont know if my new problem is just me as i cant get my old profile to work, i had also copied it and i cant get that copy to work either. Anyway i will make a new issue for that if i cant resolve myself. Regards PEEP

**Comment by jdahlblom** [comment]
Important!
Old profile, is it old profile made with 4.0.64_alpha or 4.0.62_alpha (and earlier)?
Because 4.0.64_alpha had a bug which prohibited opening of profiles made with earlier version. This is corrected in 4.0.66_alpha.

**Comment by shaky1963** [comment]
Ok this is what i believed i have done. I had made a profile in 4.0.62 which was working. In 4.0.64 this profile did not work (silly me even though you have warnings to have a backup copy , i did not have one.) I am pretty sure the data in the config file got wiped. So i then made another profile in 4.0.64 and also made a backup copy. When you released 4.0.66 my profile from 4.064 would not work. The data was still in the config file this time but would not show up in DCSFP . This time i had a back up copy, but i could not get this to work either. i tried to enter manually in the config file as well and i could not get it to go. I have now made another small profile in 4.066 from scratch which is all working well but i do not plan to make it any bigger until another update got released so i could check if it can be used in the next update. In short i dont believe the bug which allows opening of earlier made profiles is fully resolved. Sorry i cant be a lot of help. Might have to wait until Matt-cahill tries it and makes a report.

**Comment by jdahlblom** [comment]
OK. I got an old one from Matt and via that I found what the problem was. So any profiles made with 4.0.64_alpha will not work, the rest should (pre 4.0.64_alpha).
But let's see what Matt has to say.
After this it shouldn't be any known changes, i.e. it is safe to start building a bigger profile.
In the future if a profile doesn't work in a new release, don't panic, just inform me and provide the profile and I will look into it!

**Comment by shaky1963** [comment]
Hi, Below is the error log 

17.05.2020 09:55:08  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 09:55:08  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 09:55:08  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 09:55:08  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 07:57:13  version : 1.0.260.7996

System.Exception
1003351 Error in CopyValues() : Please enter a valid value (positive whole number). Value found : []
 DCS-BIOS Input is AP_ALT_HOLD_BTN / SET_STATE
   at DCSFlightpanels.Windows.DCSBiosInputWindow.CopyValues()
   at DCSFlightpanels.Windows.DCSBiosInputWindow.ButtonOkClick(Object sender, RoutedEventArgs e)

17.05.2020 05:30:24  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 05:30:24  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 05:30:24  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 05:30:24  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 05:09:02  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 05:09:02  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 05:09:02  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 05:09:02  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 04:47:56  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 04:47:56  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 04:47:56  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 04:47:56  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:29:04  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 11:29:04  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:29:04  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:29:04  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:20:01  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 11:20:01  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:20:01  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:20:01  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:03:06  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 11:03:06  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:03:06  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 11:03:06  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 10:54:13  version : 1.0.260.7996

Newtonsoft.Json.JsonSerializationException
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NonVisuals.StreamDeck.StreamDeckLayerHandler.ImportJSONSettings(String jsonText)
   at NonVisuals.StreamDeck.StreamDeckPanel.ImportSettings(List`1 settings)
   at NonVisuals.ProfileHandler.ProfileReadFromFileEventHandler.Invoke(Object sender, SettingsReadFromFileEventArgs e)
   at NonVisuals.ProfileHandler.SendSettingsReadEvent()

17.05.2020 10:54:13  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 10:54:13  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'. Path '$values[0].LayerStreamDeckButtons', line 7, position 31.

17.05.2020 10:54:13  version : 1.0.260.7996
JSON Error.
Could not find member 'LayerStreamDeckButtons' on object of type 'StreamDeckLayer'.

**Comment by shaky1963** [comment]
Just a quick question
Are you still accepting feature requests or do you want a break from programming?

**Comment by jdahlblom** [comment]
That is exactly the error you get from a profile made with 4.0.64_alpha. By mistake I had change a variable name in that release. If you change ´LayerStreamDeckButtons´ to ´StreamDeckButtons´ it should open.

**Comment by jdahlblom** [comment]
Well now I would really like to have a break. It has been **a lot** of programming lately.
> 
> 
> Just a quick question
> Are you still accepting feature requests or do you want a break from programming?

**Comment by jdahlblom** [comment]
If you have any ideas on useful features just make a "Feature requiest xxxxxx" issue and I will look into it at some later point.

**Comment by shaky1963** [comment]
If you change ´LayerStreamDeckButtons´ to ´StreamDeckButtons´
That fixed it , thank you
