### ISSUE TITLE
Annoying and unhelpful intermittent error when binding keystrokes

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#85]
When trying to bind and change keystroke bindings, intermittently a dialog error pops up.

You can clear the error but you can no longer make any changes to that switch's bindings without it generating this error again. 

Sometimes you can clear it by switching from one panel to another or saving / reloading / quit and relaunch, but it's annoying and very unhelpful.

Here's the text version of the error:

 "Details logged to error log.NonVisuals    Object reference not set to an instance of an object."

Here is the error.log.txt when it's spewing this error:

20.06.2020 12:26:36  version : 1.0.269.3388

System.NullReferenceException
Object reference not set to an instance of an object.
   at NonVisuals.Saitek.KeyBindingPZ55.SetNegators(HashSet`1 knobBindings)
   at NonVisuals.Saitek.SwitchPanelPZ55.AddOrUpdateSingleKeyBinding(SwitchPanelPZ55Keys switchPanelPZ55Key, String keys, KeyPressLength keyPressLength, Boolean whenTurnedOn)
   at DCSFlightpanels.PanelUserControls.SwitchPanelPZ55UserControl.UpdateKeyBindingProfileSimpleKeyStrokes(PZ55TextBox textBox)

20.06.2020 12:26:34  version : 1.0.269.3388

System.NullReferenceException
Object reference not set to an instance of an object.
   at NonVisuals.Saitek.KeyBindingPZ55.SetNegators(HashSet`1 knobBindings)
   at NonVisuals.Saitek.SwitchPanelPZ55.AddOrUpdateSingleKeyBinding(SwitchPanelPZ55Keys switchPanelPZ55Key, String keys, KeyPressLength keyPressLength, Boolean whenTurnedOn)
   at DCSFlightpanels.PanelUserControls.SwitchPanelPZ55UserControl.UpdateKeyBindingProfileSimpleKeyStrokes(PZ55TextBox textBox)

20.06.2020 12:26:32  version : 1.0.269.3388

System.NullReferenceException
Object reference not set to an instance of an object.
   at NonVisuals.Saitek.KeyBindingPZ55.SetNegators(HashSet`1 knobBindings)
   at NonVisuals.Saitek.SwitchPanelPZ55.AddOrUpdateSingleKeyBinding(SwitchPanelPZ55Keys switchPanelPZ55Key, String keys, KeyPressLength keyPressLength, Boolean whenTurnedOn)
   at DCSFlightpanels.PanelUserControls.SwitchPanelPZ55UserControl.UpdateKeyBindingProfileSimpleKeyStrokes(PZ55TextBox textBox)

20.06.2020 12:26:29  version : 1.0.269.3388

System.NullReferenceException
Object reference not set to an instance of an object.
   at NonVisuals.Saitek.KeyBindingPZ55.SetNegators(HashSet`1 knobBindings)
   at NonVisuals.Saitek.SwitchPanelPZ55.AddOrUpdateSingleKeyBinding(SwitchPanelPZ55Keys switchPanelPZ55Key, String keys, KeyPressLength keyPressLength, Boolean whenTurnedOn)
   at DCSFlightpanels.PanelUserControls.SwitchPanelPZ55UserControl.UpdateKeyBindingProfileSimpleKeyStrokes(PZ55TextBox textBox)

**Comment by jdahlblom** [comment]
I will try to reproduce this.

**Comment by jdahlblom** [comment]
Are you using Windows 7?

**Comment by ZoeESummers** [comment]
Nope. Win 10 pro 2004

**Comment by jdahlblom** [comment]
Are you using DCSFP mainly as a key emulator, not using DCS-BIOS at all?

**Comment by ZoeESummers** [comment]
Both; when I use DCS, it's using DCS Bios. When I use it for Elite Dangerous or Star Citizen, it's a keyboard emulator.

**Comment by jdahlblom** [comment]
One user reported similar problems and by updating the. NET framework the problems disappeared. I think 4.7.1 is used.

**Comment by jdahlblom** [comment]
.NET 4.7.2 is the version used! Do you have that installed and updated?
